name: Build and push Docker image to ECR
on:
  push:
    branches:
      - main
env:
  MONGODB_ATLAS_USERNAME: ayush vashistha
  
  MONGODB_ATLAS_PROJECT_ID: 643baf793ce9aa61105a26c1
  MONGODB_ATLAS_CLUSTER_NAME: ayush-test
  
  MONGODB_ATLAS_FUNCTION_NAME: ayush_function
  #FILE_PATH: index.js
jobs:
  use-atlas-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Atlas CLI
        uses: andreaangiolillo/atlas-cli-github-action@v1.1.0
        with:
         public-key: vikvqvrh
         private-key: fee8edd1-014f-47e0-a9da-ca17967d4014
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version
      - name: Deploy function
        uses: supercharge/mongodb-atlas-deploy@v1
        with:
          public_key: vikvqvrh
          private_key: fee8edd1-014f-47e0-a9da-ca17967d4014
          project_id: 643baf7961e6283573a0360d
          cluster_name: ayush-test
          database_name: myFirstDatabase
          function_name: ayush_function
          source_path: App.js







       
      
    







    
