name: Build and push Docker image to ECR
on:
  push:
    branches:
      - main
env:
  MONGODB_ATLAS_USERNAME: "ayush vashistha"
  MONGODB_ATLAS_API_KEY: "xd7zqSCX7Pk6BThPrPMk1OfdgOxh2agrhKesZynTNB8ug20Lt3qE74sBhQ3Tobn8"
  MONGODB_ATLAS_PROJECT_ID: "643baf7961e6283573a0360d"
  MONGODB_ATLAS_CLUSTER_NAME: "ayush-test"
#  MONGODB_ATLAS_DATABASE_NAME: <your database name>
  MONGODB_ATLAS_FUNCTION_NAME: "ayush_function"
  FILE_PATH: NODE-JS/App.js /
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: 168933414344.dkr.ecr.ap-south-1.amazonaws.com
          IMAGE_NAME: my-repository
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
          docker push $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
       
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.8"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

     

  
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install -g mongodb-stitch-cli
      - name: Authenticate to MongoDB Atlas
        run: |
          echo "xd7zqSCX7Pk6BThPrPMk1OfdgOxh2agrhKesZynTNB8ug20Lt3qE74sBhQ3Tobn8" | stitch-cli login --api-key 
      - name: Update function code
        run: |
          stitch-cli \
            --username=${MONGODB_ATLAS_USERNAME} \
            --projectId=${MONGODB_ATLAS_PROJECT_ID} \
            --clusterName=${MONGODB_ATLAS_CLUSTER_NAME} \
            functions update \
            --name=${MONGODB_ATLAS_FUNCTION_NAME} \
            --source="$(cat ${FILE_PATH})"









    
