name: Build and push Docker image to ECR
on:
  push:
    branches:
      - main
env:
  MONGODB_ATLAS_USERNAME: ayush vashistha
  
  MONGODB_ATLAS_PROJECT_ID: 643baf793ce9aa61105a26c1
  MONGODB_ATLAS_CLUSTER_NAME: ayush-test
  
  MONGODB_ATLAS_FUNCTION_NAME: ayush_function
  FILE_PATH: App.js
jobs:
  use-atlas-cli:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Atlas CLI
        uses: andreaangiolillo/atlas-cli-github-action@v1.1.0
        with:
         public-key: vikvqvrh
         private-key: 643baf7961e6283573a0360d
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

         
      - name: Use AtlasCLI
        shell: bash
        run: atlas --version
      - name: Install MongoDB Stitch CLI
        run: |
         curl https://s3.amazonaws.com/stitch-sdks/cli/v4/stitch-cli-v4.6.0-linux-x64.tar.gz -o stitch-cli.tar.gz
         tar -zxvf stitch-cli.tar.gz
         sudo mv stitch-cli-v4.6.0-linux-x64/stitch /usr/local/bi
      - name: Update MongoDB Stitch function
        env:
         FUNCTION_NAME: ayush_function # Replace with the name of your function
        run: |
         file_contents="$(cat App.js)"
         stitch functions update --name "${FUNCTION_NAME}" --source "${file_contents}"


  
    







    
